### ISSUE TITLE
Get changes from Mockup to www.farmer.tf.io

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/www_farmer_threefold.io#7]
Get changes to farming landingpage to make it clear to all who go there:

- what farming is
- how they can get involved

https://docs.google.com/presentation/d/1SHm95C0m34MRo2PaCOJFrKafCV9QzzDLEqO-tj-XOXY/edit#slide=id.p

**Comment by sasha-astiadi** [comment]
whats the status @VonSub please update. this project us expired already. if necessary please move the card to the latest project
